/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's repo.
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WechatSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  backendUrl: "http://localhost:8787",
  deviceId: "",
  deviceName: "\u6211\u7684\u7535\u8111",
  deviceToken: "",
  pairingCodeInput: "",
  autoSyncOnStartup: true,
  syncIntervalMinutes: 5,
  inboxFolder: "\u5FAE\u4FE1\u6536\u85CF",
  autoLinkByTitle: true,
  aiBaseUrl: "https://api.openai.com/v1",
  aiApiKey: "",
  aiModel: "gpt-4o-mini",
  conversationFolder: "AI\u5BF9\u8BDD",
  resumeLastConversation: true,
  systemPrompt: "\u4F60\u662F\u4E00\u4E2A\u77E5\u8BC6\u7BA1\u7406\u52A9\u624B\uFF0C\u5E2E\u52A9\u7528\u6237\u6574\u7406\u548C\u8FDE\u63A5\u4ED6\u7684\u7B14\u8BB0\u3002\u7528\u4E2D\u6587\u56DE\u7B54\uFF0C\u7B80\u6D01\u6709\u6761\u7406\u3002"
};
var WechatSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "\u540E\u7AEF\u8FDE\u63A5" });
    new import_obsidian.Setting(containerEl).setName("\u540E\u7AEF\u5730\u5740").setDesc("sync-backend \u7684\u5730\u5740\uFF0C\u624B\u673A\u771F\u673A\u8C03\u8BD5\u7528\u7535\u8111\u5C40\u57DF\u7F51 IP").addText(
      (t) => t.setPlaceholder("http://localhost:8787").setValue(this.plugin.settings.backendUrl).onChange(async (v) => {
        this.plugin.settings.backendUrl = v.trim();
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u7ED1\u5B9A Obsidian" });
    containerEl.createEl("p", {
      text: "1. \u5728\u5FAE\u4FE1\u5C0F\u7A0B\u5E8F\u300C\u7ED1\u5B9A Obsidian\u300D\u9875\u70B9\u51FB\u300C\u67E5\u770B\u7ED1\u5B9A\u7801\u300D\n2. \u628A 6 \u4F4D\u7ED1\u5B9A\u7801\u586B\u5165\u4E0B\u65B9\uFF0C\u70B9\u51FB\u300C\u7ACB\u5373\u7ED1\u5B9A\u300D\n3. \u7ED1\u5B9A\u6210\u529F\u540E\uFF0C\u63D2\u4EF6\u4F1A\u81EA\u52A8\u62C9\u53D6\u5C0F\u7A0B\u5E8F\u6536\u96C6\u7684\u5185\u5BB9"
    });
    new import_obsidian.Setting(containerEl).setName("\u7ED1\u5B9A\u7801").setDesc("\u4ECE\u5C0F\u7A0B\u5E8F\u83B7\u53D6\u7684 6 \u4F4D\u5B57\u7B26").addText(
      (t) => t.setPlaceholder("\u4F8B\u5982 A1B2C3").setValue(this.plugin.settings.pairingCodeInput).onChange(async (v) => {
        this.plugin.settings.pairingCodeInput = v.trim().toUpperCase();
        await this.plugin.saveSettings();
      })
    ).addButton(
      (b) => b.setButtonText("\u7ACB\u5373\u7ED1\u5B9A").setCta().onClick(async () => {
        await this.plugin.bindWithCode(this.plugin.settings.pairingCodeInput);
        this.display();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u672C\u673A\u8BBE\u5907\u540D").addText(
      (t) => t.setValue(this.plugin.settings.deviceName).onChange(async (v) => {
        this.plugin.settings.deviceName = v.trim() || "\u6211\u7684\u7535\u8111";
        await this.plugin.saveSettings();
      })
    );
    const bindStatus = containerEl.createEl("div", { cls: "sync-bind-status" });
    if (this.plugin.settings.deviceToken) {
      bindStatus.createEl("p", {
        text: `\u2705 \u5DF2\u7ED1\u5B9A\uFF1A${this.plugin.settings.deviceName}\uFF08${this.plugin.settings.deviceToken.slice(0, 8)}...\uFF09`,
        cls: "sync-bind-ok"
      });
      new import_obsidian.Setting(containerEl).setName("\u89E3\u9664\u7ED1\u5B9A").setDesc("\u6E05\u9664\u672C\u673A deviceToken\uFF0C\u9700\u8981\u91CD\u65B0\u8F93\u5165\u7ED1\u5B9A\u7801").addButton(
        (b) => b.setButtonText("\u89E3\u9664\u7ED1\u5B9A").onClick(async () => {
          this.plugin.unbindDevice();
          this.display();
        })
      );
    } else {
      bindStatus.createEl("p", { text: "\u23F3 \u672A\u7ED1\u5B9A\uFF0C\u8BF7\u8F93\u5165\u5C0F\u7A0B\u5E8F\u4E0A\u7684\u7ED1\u5B9A\u7801", cls: "sync-bind-wait" });
    }
    containerEl.createEl("h3", { text: "\u81EA\u52A8\u540C\u6B65" });
    new import_obsidian.Setting(containerEl).setName("\u542F\u52A8\u540E\u81EA\u52A8\u540C\u6B65").setDesc("Obsidian \u6253\u5F00\u540E\u81EA\u52A8\u62C9\u53D6\u5C0F\u7A0B\u5E8F\u5F85\u540C\u6B65\u5185\u5BB9").addToggle(
      (t) => t.setValue(this.plugin.settings.autoSyncOnStartup).onChange(async (v) => {
        this.plugin.settings.autoSyncOnStartup = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u81EA\u52A8\u8F6E\u8BE2\u95F4\u9694\uFF08\u5206\u949F\uFF09").setDesc("0 \u8868\u793A\u53EA\u624B\u52A8\u540C\u6B65\uFF1B\u5EFA\u8BAE 5 \u5206\u949F").addSlider(
      (s) => s.setLimits(0, 30, 1).setValue(this.plugin.settings.syncIntervalMinutes).setDynamicTooltip().onChange(async (v) => {
        this.plugin.settings.syncIntervalMinutes = v;
        await this.plugin.saveSettings();
        this.plugin.restartSyncInterval();
      })
    );
    containerEl.createEl("h3", { text: "\u77E5\u8BC6\u5E93" });
    new import_obsidian.Setting(containerEl).setName("\u6536\u85CF\u6587\u4EF6\u5939").setDesc("\u5FAE\u4FE1\u5185\u5BB9\u540C\u6B65\u8FDB\u6765\u5B58\u653E\u7684\u6587\u4EF6\u5939").addText(
      (t) => t.setPlaceholder("\u5FAE\u4FE1\u6536\u85CF").setValue(this.plugin.settings.inboxFolder).onChange(async (v) => {
        this.plugin.settings.inboxFolder = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6309\u6807\u9898\u81EA\u52A8\u4E92\u94FE").setDesc("\u5BFC\u5165\u65F6\u628A\u6B63\u6587\u4E2D\u51FA\u73B0\u7684\u5176\u4ED6\u7B14\u8BB0\u6807\u9898\u66FF\u6362\u4E3A [[\u53CC\u94FE]]").addToggle(
      (t) => t.setValue(this.plugin.settings.autoLinkByTitle).onChange(async (v) => {
        this.plugin.settings.autoLinkByTitle = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "AI \u5BF9\u8BDD" });
    new import_obsidian.Setting(containerEl).setName("API Base URL").setDesc("OpenAI \u517C\u5BB9\u63A5\u53E3\u5730\u5740").addText(
      (t) => t.setPlaceholder("https://api.openai.com/v1").setValue(this.plugin.settings.aiBaseUrl).onChange(async (v) => {
        this.plugin.settings.aiBaseUrl = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API Key").addText(
      (t) => t.setPlaceholder("sk-...").setValue(this.plugin.settings.aiApiKey).onChange(async (v) => {
        this.plugin.settings.aiApiKey = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").addText(
      (t) => t.setPlaceholder("gpt-4o-mini").setValue(this.plugin.settings.aiModel).onChange(async (v) => {
        this.plugin.settings.aiModel = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u5BF9\u8BDD\u6587\u4EF6\u5939").setDesc("\u6BCF\u6B21\u5BF9\u8BDD\u81EA\u52A8\u5B58\u6863\u5230\u7684\u6587\u4EF6\u5939").addText(
      (t) => t.setPlaceholder("AI\u5BF9\u8BDD").setValue(this.plugin.settings.conversationFolder).onChange(async (v) => {
        this.plugin.settings.conversationFolder = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7EED\u63A5\u4E0A\u6B21\u5BF9\u8BDD").setDesc("\u6253\u5F00\u5BF9\u8BDD\u89C6\u56FE\u65F6\u81EA\u52A8\u52A0\u8F7D\u6700\u8FD1\u7684\u5BF9\u8BDD\u6587\u6863\uFF0C\u63A5\u7740\u804A").addToggle(
      (t) => t.setValue(this.plugin.settings.resumeLastConversation).onChange(async (v) => {
        this.plugin.settings.resumeLastConversation = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF\u63D0\u793A\u8BCD").addTextArea(
      (t) => t.setValue(this.plugin.settings.systemPrompt).onChange(async (v) => {
        this.plugin.settings.systemPrompt = v;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/api.ts
var import_obsidian2 = require("obsidian");
var SyncApi = class {
  constructor(baseUrl, deviceToken) {
    this.baseUrl = baseUrl;
    this.deviceToken = deviceToken;
  }
  async req(method, path, body) {
    const url = this.baseUrl.replace(/\/+$/, "") + path;
    const headers = {
      "Content-Type": "application/json"
    };
    if (this.deviceToken) {
      headers["x-device-token"] = this.deviceToken;
    }
    const resp = await (0, import_obsidian2.requestUrl)({
      url,
      method,
      headers,
      body: body ? JSON.stringify(body) : void 0
    });
    if (resp.status >= 400) {
      const text = typeof resp.text === "string" ? resp.text : JSON.stringify(resp.json || {});
      throw new Error(`\u540E\u7AEF\u9519\u8BEF ${resp.status}: ${text}`);
    }
    return resp.json;
  }
  bindDevice(input) {
    return this.req("POST", "/api/devices/bind", input);
  }
  listInbox(pendingOnly = true) {
    return this.req("GET", `/api/inbox?pendingOnly=${pendingOnly}`);
  }
  getInboxItem(id) {
    return this.req("GET", `/api/inbox/${encodeURIComponent(id)}`);
  }
  markInboxSynced(id, obsidianPath) {
    return this.req("POST", `/api/inbox/${encodeURIComponent(id)}/synced`, { obsidianPath });
  }
  pushNote(note) {
    return this.req("POST", "/api/notes", note);
  }
  listNotes() {
    return this.req("GET", "/api/notes");
  }
};

// src/sync/pull.ts
var import_obsidian4 = require("obsidian");

// src/utils/markdown.ts
function sanitizeFilename(name) {
  return name.replace(/[\\/:*?"<>|#^[\]]/g, "_").replace(/\s+/g, " ").trim().slice(0, 80) || "\u672A\u547D\u540D";
}
async function ensureFolder(vault, folderPath) {
  if (!folderPath || folderPath === "/")
    return;
  const parts = folderPath.split("/").filter(Boolean);
  let cur = "";
  for (const p of parts) {
    cur = cur ? `${cur}/${p}` : p;
    if (!vault.getAbstractFileByPath(cur)) {
      await vault.createFolder(cur);
    }
  }
}
function buildFrontmatter(fm) {
  const lines = ["---"];
  for (const [k, v] of Object.entries(fm)) {
    if (Array.isArray(v)) {
      const items = v.map((x) => `"${String(x).replace(/"/g, '\\"')}"`).join(", ");
      lines.push(`${k}: [${items}]`);
    } else if (typeof v === "string") {
      lines.push(`${k}: "${v.replace(/"/g, '\\"')}"`);
    } else if (v === null || v === void 0) {
      lines.push(`${k}: ""`);
    } else {
      lines.push(`${k}: ${v}`);
    }
  }
  lines.push("---");
  return lines.join("\n");
}
function getFrontmatterTags(file, cache) {
  var _a;
  const t = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags;
  if (Array.isArray(t))
    return t;
  if (typeof t === "string")
    return [t];
  return [];
}

// src/sync/links.ts
var import_obsidian3 = require("obsidian");
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function injectTitleLinks(content, titles) {
  let out = content;
  for (const t of titles) {
    if (t.length < 2)
      continue;
    const re = new RegExp(`(?<!\\w)(?<![[)${escapeRegExp(t)}(?!\\w)(?!]])`, "g");
    out = out.replace(re, `[[${t}]]`);
  }
  return out;
}
async function updateTagHubs(app, items, indexFolder) {
  const byTag = /* @__PURE__ */ new Map();
  for (const it of items) {
    for (const tag of it.tags) {
      const arr = byTag.get(tag) || [];
      arr.push(it.title);
      byTag.set(tag, arr);
    }
  }
  if (byTag.size === 0)
    return;
  await ensureFolder(app.vault, indexFolder);
  for (const [tag, titles] of byTag) {
    const path = `${indexFolder}/${sanitizeFilename(tag)}.md`;
    const body = `# ${tag}

> \u81EA\u52A8\u7EF4\u62A4\u7684\u6807\u7B7E\u7D22\u5F15\uFF0C\u4E0B\u9762\u7684\u7B14\u8BB0\u90FD\u6253\u4E86 \`` + tag + "` \u6807\u7B7E\u3002\n\n" + titles.map((t) => `- [[${t}]]`).join("\n") + "\n";
    const existing = app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian3.TFile) {
      await app.vault.modify(existing, body);
    } else {
      await app.vault.create(path, body);
    }
  }
}

// src/sync/pull.ts
function buildNoteContent(item) {
  const fm = buildFrontmatter({
    type: item.type,
    source: item.source || "Obsidian \u5185\u5BB9\u540C\u6B65\u52A9\u624B",
    url: item.url || "",
    tags: item.tags,
    wechat_id: item.id,
    importedAt: (/* @__PURE__ */ new Date()).toISOString()
  });
  const media = (item.mediaUrls || []).map((u) => `![](${u})`).join("\n");
  const related = item.tags.length > 0 ? "\n## \u5173\u8054\n" + item.tags.map((t) => `- [[\u7D22\u5F15/${t}]]`).join("\n") + "\n" : "";
  return `${fm}
# ${item.title}

${item.content}

${media}
${related}`;
}
async function linkWithinBatch(plugin, titles) {
  if (titles.length < 2 || !plugin.settings.autoLinkByTitle)
    return;
  const folder = plugin.settings.inboxFolder;
  for (const title of titles) {
    const path = `${folder}/${sanitizeFilename(title)}.md`;
    const file = plugin.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian4.TFile))
      continue;
    const content = await plugin.app.vault.cachedRead(file);
    const others = titles.filter((t) => t !== title);
    const linked = injectTitleLinks(content, others);
    if (linked !== content) {
      await plugin.app.vault.modify(file, linked);
    }
  }
}
async function pullPending(plugin) {
  const api = plugin.getApi();
  const settings = plugin.settings;
  let items = [];
  try {
    items = await api.listInbox(true);
  } catch (e) {
    new import_obsidian4.Notice("\u62C9\u53D6\u5931\u8D25\uFF1A" + e.message);
    return 0;
  }
  if (items.length === 0) {
    new import_obsidian4.Notice("\u6CA1\u6709\u5F85\u540C\u6B65\u7684\u5FAE\u4FE1\u5185\u5BB9");
    return 0;
  }
  await ensureFolder(plugin.app.vault, settings.inboxFolder);
  const importedTitles = [];
  const imported = [];
  for (const item of items) {
    const safe = sanitizeFilename(item.title);
    const path = `${settings.inboxFolder}/${safe}.md`;
    const existing = plugin.app.vault.getAbstractFileByPath(path);
    if (existing instanceof import_obsidian4.TFile) {
      await api.markInboxSynced(item.id, path);
      continue;
    }
    await plugin.app.vault.create(path, buildNoteContent(item));
    importedTitles.push(item.title);
    imported.push({ title: item.title, tags: item.tags });
    await api.markInboxSynced(item.id, path);
  }
  await linkWithinBatch(plugin, importedTitles);
  await updateTagHubs(plugin.app, imported, `${settings.inboxFolder}/\u7D22\u5F15`);
  new import_obsidian4.Notice(`\u5DF2\u540C\u6B65 ${importedTitles.length} \u6761\u5230\u300C${settings.inboxFolder}\u300D`);
  return importedTitles.length;
}

// src/sync/push.ts
var import_obsidian5 = require("obsidian");
async function pushActiveNote(plugin) {
  const view = plugin.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
  const file = view == null ? void 0 : view.file;
  if (!file) {
    new import_obsidian5.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u7BC7\u8981\u53D1\u5E03\u7684\u7B14\u8BB0");
    return;
  }
  const content = await plugin.app.vault.cachedRead(file);
  const cache = plugin.app.metadataCache.getFileCache(file);
  const tags = getFrontmatterTags(file, cache);
  try {
    await plugin.getApi().pushNote({ title: file.basename, content, tags });
    new import_obsidian5.Notice(`\u5DF2\u53D1\u5E03\u300C${file.basename}\u300D\u5230\u5C0F\u7A0B\u5E8F`);
  } catch (e) {
    new import_obsidian5.Notice("\u53D1\u5E03\u5931\u8D25\uFF1A" + e.message);
  }
}

// src/conversation/conversationView.ts
var import_obsidian7 = require("obsidian");

// src/conversation/aiClient.ts
var import_obsidian6 = require("obsidian");
async function chatCompletion(opts) {
  var _a, _b, _c, _d;
  const url = opts.baseUrl.replace(/\/+$/, "") + "/chat/completions";
  const resp = await (0, import_obsidian6.requestUrl)({
    url,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${opts.apiKey}`
    },
    body: JSON.stringify({
      model: opts.model,
      messages: opts.messages,
      temperature: 0.7
    })
  });
  if (resp.status >= 400) {
    throw new Error(`AI \u9519\u8BEF ${resp.status}: ${resp.text || ""}`);
  }
  const data = resp.json;
  return (_d = (_c = (_b = (_a = data == null ? void 0 : data.choices) == null ? void 0 : _a[0]) == null ? void 0 : _b.message) == null ? void 0 : _c.content) != null ? _d : "";
}

// src/conversation/store.ts
var PREFIX = "\u5BF9\u8BDD-";
function formatStamp(d) {
  const p = (n) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}-${p(d.getHours())}${p(d.getMinutes())}`;
}
async function findLatestConversation(app, folder) {
  const files = app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(folder + "/") && f.basename.startsWith(PREFIX));
  if (files.length === 0)
    return null;
  files.sort((a, b) => b.basename.localeCompare(a.basename));
  return files[0];
}
async function createConversationFile(app, folder) {
  await ensureFolder(app.vault, folder);
  const stamp = formatStamp(/* @__PURE__ */ new Date());
  const path = `${folder}/${PREFIX}${stamp}.md`;
  const fm = buildFrontmatter({
    conversationId: stamp,
    createdAt: (/* @__PURE__ */ new Date()).toISOString(),
    type: "conversation"
  });
  return app.vault.create(path, `${fm}
# \u5BF9\u8BDD ${stamp}
`);
}
async function appendTurn(app, file, role, text) {
  const existing = await app.vault.cachedRead(file);
  const header = role === "user" ? "## \u{1F464} \u7528\u6237" : "## \u{1F916} \u52A9\u624B";
  const updated = `${existing}

${header}

${text}
`;
  await app.vault.modify(file, updated);
}
function loadTranscript(content) {
  var _a, _b;
  const msgs = [];
  const matches = [...content.matchAll(/##\s*(?:👤\s*)?用户|##\s*(?:🤖\s*)?助手/g)];
  for (let i = 0; i < matches.length; i++) {
    const m = matches[i];
    const role = m[0].includes("\u7528\u6237") ? "user" : "assistant";
    const start = ((_a = m.index) != null ? _a : 0) + m[0].length;
    const end = i + 1 < matches.length ? (_b = matches[i + 1].index) != null ? _b : content.length : content.length;
    const text = content.slice(start, end).trim();
    if (text)
      msgs.push({ role, content: text });
  }
  return msgs;
}

// src/conversation/conversationView.ts
var VIEW_TYPE_CONVERSATION = "wechat-inbox-sync-conversation";
var ConversationView = class extends import_obsidian7.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.file = null;
    this.busy = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CONVERSATION;
  }
  getDisplayText() {
    return "AI \u5BF9\u8BDD";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    const settings = this.plugin.settings;
    const state = this.leaf.getViewState().state;
    const forceNew = (state == null ? void 0 : state.forceNew) === true;
    if (forceNew || !settings.resumeLastConversation) {
      this.file = await createConversationFile(this.app, settings.conversationFolder);
    } else {
      const latest = await findLatestConversation(this.app, settings.conversationFolder);
      if (latest) {
        this.file = latest;
        this.messages = loadTranscript(await this.app.vault.cachedRead(latest));
      } else {
        this.file = await createConversationFile(this.app, settings.conversationFolder);
      }
    }
    this.render();
    for (const m of this.messages) {
      this.renderMessage(m.role, m.content);
    }
    this.scrollToBottom();
  }
  async onClose() {
    this.contentEl.empty();
  }
  render() {
    const root = this.contentEl;
    root.empty();
    root.addClass("ws-conversation");
    const header = root.createEl("div", { cls: "ws-conv-header" });
    header.textContent = this.file ? `\u5BF9\u8BDD\u6587\u6863\uFF1A${this.file.path}\uFF08\u81EA\u52A8\u5B58\u6863\uFF09` : "AI \u5BF9\u8BDD";
    this.logEl = root.createEl("div", { cls: "ws-conv-log" });
    const inputRow = root.createEl("div", { cls: "ws-conv-input" });
    this.inputEl = inputRow.createEl("textarea", {
      cls: "ws-conv-textarea",
      attr: { placeholder: "\u8F93\u5165\u6D88\u606F\uFF0CEnter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C" }
    });
    this.sendBtn = inputRow.createEl("button", { text: "\u53D1\u9001" });
    this.sendBtn.addEventListener("click", () => this.send());
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.send();
      }
    });
  }
  renderMessage(role, text) {
    const wrap = this.logEl.createEl("div", {
      cls: `ws-msg ${role === "user" ? "ws-msg-user" : "ws-msg-assistant"}`
    });
    wrap.createEl("div", {
      cls: "ws-msg-role",
      text: role === "user" ? "\u6211" : "\u52A9\u624B"
    });
    wrap.createEl("div", { text });
  }
  scrollToBottom() {
    this.logEl.scrollTop = this.logEl.scrollHeight;
  }
  async send() {
    if (this.busy)
      return;
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    if (!this.plugin.settings.aiApiKey) {
      new import_obsidian7.Notice("\u8BF7\u5148\u5728\u63D2\u4EF6\u8BBE\u7F6E\u91CC\u586B\u5199 AI API Key");
      return;
    }
    this.inputEl.value = "";
    await this.addMessage("user", text);
    this.busy = true;
    this.sendBtn.disabled = true;
    this.sendBtn.setText("\u751F\u6210\u4E2D\u2026");
    try {
      const settings = this.plugin.settings;
      const messages = [
        { role: "system", content: settings.systemPrompt },
        ...this.messages
      ];
      const reply = await chatCompletion({
        baseUrl: settings.aiBaseUrl,
        apiKey: settings.aiApiKey,
        model: settings.aiModel,
        messages
      });
      await this.addMessage("assistant", reply);
    } catch (e) {
      new import_obsidian7.Notice("AI \u51FA\u9519\uFF1A" + e.message);
    } finally {
      this.busy = false;
      this.sendBtn.disabled = false;
      this.sendBtn.setText("\u53D1\u9001");
    }
  }
  async addMessage(role, text) {
    this.messages.push({ role, content: text });
    this.renderMessage(role, text);
    this.scrollToBottom();
    if (this.file) {
      await appendTurn(this.app, this.file, role, text);
    }
  }
};

// src/main.ts
function generateDeviceId() {
  return "obs-" + Array.from({ length: 16 }, () => Math.floor(Math.random() * 36).toString(36)).join("");
}
var WechatSyncPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.syncIntervalId = null;
  }
  async onload() {
    await this.loadSettings();
    if (!this.settings.deviceId) {
      this.settings.deviceId = generateDeviceId();
      await this.saveSettings();
    }
    this.api = new SyncApi(this.settings.backendUrl, this.settings.deviceToken);
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar("\u5C31\u7EEA");
    this.addRibbonIcon("refresh-cw", "\u540C\u6B65\u5FAE\u4FE1\u5185\u5BB9", () => this.syncNow());
    this.addCommand({
      id: "pull-wechat",
      name: "\u62C9\u53D6\u5FAE\u4FE1\u5185\u5BB9\u5230\u77E5\u8BC6\u5E93",
      callback: () => this.syncNow()
    });
    this.addCommand({
      id: "push-note",
      name: "\u53D1\u5E03\u5F53\u524D\u7B14\u8BB0\u5230\u5C0F\u7A0B\u5E8F",
      callback: () => this.pushNow()
    });
    this.addCommand({
      id: "open-conversation",
      name: "\u6253\u5F00 AI \u5BF9\u8BDD\uFF08\u7EED\u63A5\u4E0A\u6B21\uFF09",
      callback: () => this.activateConversation(false)
    });
    this.addCommand({
      id: "new-conversation",
      name: "\u65B0\u5EFA\u5BF9\u8BDD",
      callback: () => this.activateConversation(true)
    });
    this.addCommand({
      id: "rebuild-links",
      name: "\u91CD\u5EFA\u53CC\u94FE\u7D22\u5F15",
      callback: () => this.rebuildLinks()
    });
    this.registerView(VIEW_TYPE_CONVERSATION, (leaf) => new ConversationView(leaf, this));
    this.addSettingTab(new WechatSyncSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      if (this.settings.autoSyncOnStartup && this.settings.deviceToken) {
        this.syncNow(false);
      }
      this.restartSyncInterval();
    });
  }
  onunload() {
    if (this.syncIntervalId) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
  }
  // 始终返回带最新设置的 API 客户端
  getApi() {
    this.api.baseUrl = this.settings.backendUrl;
    this.api.deviceToken = this.settings.deviceToken;
    return this.api;
  }
  updateStatusBar(text) {
    if (this.statusBarItem) {
      this.statusBarItem.setText(`\u5FAE\u4FE1\u540C\u6B65: ${text}`);
    }
  }
  // 绑定码配对
  async bindWithCode(code) {
    code = code.trim().toUpperCase();
    if (!/^[A-Z0-9]{6}$/.test(code)) {
      new import_obsidian8.Notice("\u7ED1\u5B9A\u7801\u5E94\u4E3A 6 \u4F4D\u5B57\u6BCD/\u6570\u5B57");
      return;
    }
    try {
      this.updateStatusBar("\u7ED1\u5B9A\u4E2D...");
      const resp = await this.getApi().bindDevice({
        code,
        deviceId: this.settings.deviceId,
        name: this.settings.deviceName
      });
      this.settings.deviceToken = resp.deviceToken;
      this.settings.pairingCodeInput = "";
      await this.saveSettings();
      new import_obsidian8.Notice(`\u2705 \u7ED1\u5B9A\u6210\u529F\uFF1A${resp.name}`);
      this.updateStatusBar("\u5DF2\u7ED1\u5B9A");
      await this.syncNow(false);
    } catch (e) {
      this.updateStatusBar("\u7ED1\u5B9A\u5931\u8D25");
      new import_obsidian8.Notice("\u7ED1\u5B9A\u5931\u8D25\uFF1A" + e.message);
    }
  }
  unbindDevice() {
    this.settings.deviceToken = "";
    this.saveSettings();
    new import_obsidian8.Notice("\u5DF2\u89E3\u9664\u7ED1\u5B9A");
    this.updateStatusBar("\u672A\u7ED1\u5B9A");
  }
  // 拉取同步
  async syncNow(notifyEmpty = true) {
    if (!this.settings.deviceToken) {
      if (notifyEmpty)
        new import_obsidian8.Notice("\u5C1A\u672A\u7ED1\u5B9A Obsidian\uFF0C\u8BF7\u5728\u63D2\u4EF6\u8BBE\u7F6E\u8F93\u5165\u5C0F\u7A0B\u5E8F\u7ED1\u5B9A\u7801");
      this.updateStatusBar("\u672A\u7ED1\u5B9A");
      return 0;
    }
    this.updateStatusBar("\u540C\u6B65\u4E2D...");
    try {
      const count = await pullPending(this);
      const time = (/* @__PURE__ */ new Date()).toLocaleTimeString();
      this.updateStatusBar(count > 0 ? `\u5DF2\u540C\u6B65 ${count} \u6761 (${time})` : `\u5DF2\u540C\u6B65 (${time})`);
      return count;
    } catch (e) {
      this.updateStatusBar("\u540C\u6B65\u5931\u8D25");
      if (notifyEmpty)
        new import_obsidian8.Notice("\u540C\u6B65\u5931\u8D25\uFF1A" + e.message);
      return 0;
    }
  }
  async pushNow() {
    if (!this.settings.deviceToken) {
      new import_obsidian8.Notice("\u5C1A\u672A\u7ED1\u5B9A Obsidian\uFF0C\u65E0\u6CD5\u53D1\u5E03\u5230\u5C0F\u7A0B\u5E8F");
      return;
    }
    try {
      await pushActiveNote(this);
    } catch (e) {
      new import_obsidian8.Notice("\u53D1\u5E03\u5931\u8D25\uFF1A" + e.message);
    }
  }
  async activateConversation(forceNew) {
    var _a;
    const leaf = (_a = this.app.workspace.getRightLeaf(false)) != null ? _a : this.app.workspace.getLeaf("tab");
    await leaf.setViewState({
      type: VIEW_TYPE_CONVERSATION,
      active: true,
      state: { forceNew }
    });
  }
  async rebuildLinks() {
    const folder = this.settings.inboxFolder;
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(folder + "/"));
    const items = files.map((f) => ({
      title: f.basename,
      tags: getFrontmatterTags(f, this.app.metadataCache.getFileCache(f))
    }));
    await updateTagHubs(this.app, items, `${folder}/\u7D22\u5F15`);
    new import_obsidian8.Notice(`\u5DF2\u91CD\u5EFA\u53CC\u94FE\u7D22\u5F15\uFF08${items.length} \u7BC7\uFF09`);
  }
  restartSyncInterval() {
    if (this.syncIntervalId) {
      window.clearInterval(this.syncIntervalId);
      this.syncIntervalId = null;
    }
    const minutes = this.settings.syncIntervalMinutes;
    if (minutes > 0 && this.settings.deviceToken) {
      this.syncIntervalId = window.setInterval(() => this.syncNow(false), minutes * 60 * 1e3);
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data != null ? data : {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.restartSyncInterval();
  }
};
